### ISSUE TITLE
ShowTaskpane URL

### ISSUE THREAD

**Issue by nvazhayil** [OfficeDev/PnP-OfficeAddins#134]
> Note: This repo is only for questions related to its samples. If you have questions about how to use office.js or the Office developer platform, please post your question on https://stackoverflow.com. Tag your question with office-js or outlook-web-addins

**Question**

Referring to the sample under https://github.com/OfficeDev/PnP-OfficeAddins/tree/master/Samples/office-contextual-tabs , the action type "ShowTaskpane" is mapped to URL "Taskpane.Url".

I want to add another button in the context tab which should launch another task pane. something similar to how we achieve this with manifest.xml
`<Control>`
 `<Action  xsi:type="ShowTaskpane">`
`		  <SourceLocation resid="myUrl" />`
`		  <Title resid="ButtonID" />`
 ` </Action>`
`</Control> `
`<bt:Url id="myUrl" DefaultValue="https://localhost:3000/myPage.html">`

How can I do this with context tabs? I understood how "ExecuteFunction" is to be done but could not find an example for "ShowTaskpane" (another panel apart from the one which can be shown/hide using office API Office.addin.showAsTaskpane() and Office.addin.hide()).

**Comment by nancy-wang** [comment]
Thanks for this question @nvazhayil ! I've tagged someone from our team to investigate further.

**Comment by davidchesnut** [comment]
Hi @nvazhayil,

To open a second task pane, you need to make the following adjustments to the ribbon JSON.
1. In the "actions" section, add an action to describe the new task pane. You must specify a "sourceLocation" value.
```json
{
   "id": "showSecondPane",
   "type": "ShowTaskpane",
   "title": "Second pane",
   "sourceLocation": "https://localhost:3000/myPage.html",
   "supportPinning": false
}
```
2. In the "tabs" where you want a button to appear to display your second task pane, add a control that references the id of the action:
```json
{
  "type": "Button",
  "id": "btnShowTaskPane2",
   "enabled": true,
   "actionId": "showSecondPane"
...
```
Some additional notes:
- Only one task pane can use the shared runtime. Any additional task panes you create will have a separate runtime.
- When you don't specify a sourceLocation, Office assumes the task pane is using the shared runtime. This will cause confusing behavior if you are attempting to use more than one. So only one task pane should be missing the sourceLocation value in the ribbon JSON (the default so to say.)
- You don't need to update the manifest XML for the above steps to work (since this puts the button on the contextual tab.)

Hope this helps,
David

**Comment by nvazhayil** [comment]
Thanks David. That worked.
