### ISSUE TITLE
Contextual tab ExecuteFunction is not working in excel on web

### ISSUE THREAD

**Issue by nvazhayil** [OfficeDev/PnP-OfficeAddins#140]
Referring to https://github.com/OfficeDev/PnP-OfficeAddins/tree/master/Samples/office-contextual-tabs, I have implemented contextual tab. There are buttons with type as "ExecuteFunction" and "ShowTaskpane". Both the types work in Excel on Windows. But, in Excel on web, clicking on a button which as type "ExecuteFunction" is not doing anything. The mapped function is not getting executed. "ShowTaskPane" works. 
The issue is only with ExecuteFunction in Excel on web. The browser console does not show anything either. 
What could be the issue? How do I find out why it's not working? Any logs that I look for?

**Comment by davidchesnut** [comment]
Hi @nvazhayil,

I suspect you are running into a bug where Office sends the same event.source.id no matter which button you click on. This only happens on the web. I wrote a function named **runRibbonAction** in the commands.js file which checks event.source.id and because it is always `btnSubmit` that is the only function called.

This is because I mapped all actions for all buttons in the ribbonJSON.js to `idRibbonAction`. Mapping all the buttons to a single action is what confuses Office in the case of web. The workaround is to instead create a separate action for each button. You'd need an `idRibbonSubmit`, `idRibbonRefresh` and so on in the "actions" section of the JSON and map each button to each individual action.

There's a fix in the works so that the original code in this sample will work on the web, but if it looks like that will take awhile, I'll update this sample to avoid creating any confusion.

Hope this helps!
David

**Comment by nvazhayil** [comment]
Hi David,

Are there any logs that are created/updated for this feature? I intend to use contextual tabs extensively. It will be helpful if there is a logging mechanism that captures issues if any.

Thanks.

**Comment by davidchesnut** [comment]
Hi @nvazhayil,

Just wanted to let you know this has been fixed. Can you please let us know if you are still seeing any issues? Sorry for the late follow-up on this. To answer your question on logging bugs, we track all customer reported bugs at https://github.com/OfficeDev/office-js/issues. If you find anything that looks like a bug, please let us know at https://github.com/OfficeDev/office-js/issues. Thanks!
