### ISSUE TITLE
Unable to get outlook add-in scopes or user identity

### ISSUE THREAD

**Issue by kudecha** [OfficeDev/PnP-OfficeAddins#187]
Hi,

I have used repository at https://github.com/OfficeDev/PnP-OfficeAddins/tree/main/Samples/auth/Outlook-Add-in-SSO to develop my first ever outlook web add-in. I have taken all steps suggested to register app to Azure as well with necessary changes to code.

The add-in requires to identify user without logging-in (similar to what Dynamics 365 outlook add-in does) and allow me to interact with microsoft graph api. This repository serves the purpose to some extent, but I am unable to sign-in silently.

All I need is to hit and execute Post function on SaveAttachmentsController.

With current [Authorize] attribute, my code won't hit the breakpoint set on Post function on SaveAttachmentsController.

If I remove [Authorize] attribute, my code will hit the breakpoint, but it won't be able to get list of scopes as ClaimsPrincipal.Current throws exception. User would then have to follow fallback login method which I would like to avoid.

Has anyone ever encountered this issue?
What should I change in code so I can keep [Authorize] attribute and still able to authorize the User silently to authenticate/communicate with Graph API?

Please help.

Regards,
Jay

**Comment by davidchesnut** [comment]
Hi @kudecha, 

Sorry this hasn't been working properly for you. I saw you also asked this same question on #178. The most likely scenario is that there is a configuration problem. I'd go through the readme steps again for the app registration and just double-check it is all configured as expected. Also double-check the manifest that it has the correct client id. Office uses the configuration information to construct the token it returns to you from getAccessToken(). 

Another thing to check is the auth token itself. When you get the value from getAccessToken, you can paste it here: https://jwt.ms/ which will decode and show you all the claims. You'll want to be sure for example the audience is set to your client id. If not it's most likely a value in the manifest or app registration not set correctly. You can check all the claims there to be sure they are being set as expected.

Hope this helps,
David

**Comment by elegault** [comment]
+1 on this exact issue! I've triple checked the app registration and the add-in manifest and the JWT decode. I've done something very similar in a different project for a PowerPoint add-in and never got this issue. But still not sure how this issue could be specific to this repo yet.  Note that I have not previously granted the app registration admin consent to the Graph scopes - I want the user to do that (it's all delegated permissions that I want anyway).  

One odd thing to add: I earlier cancelled the initial dialog to login and grant consent for the first-run scenario, as I knew the end-result will fail as I didn't complete the controller actions and I wanted to re-test this entire flow later. But...I haven't seen that login popup again - the JS code is going straight to the Ajax call for the controller action with the token retrieved from getAccessToken. I may have altered the scopes in the registration and add-in manifest later, but I've unregistered the manifest and re-added it several times.  Perhaps @kudecha and I are dealing with some weird caching issue with a bad token that isn't getting reset??

**Comment by elegault** [comment]
Some questions and thoughts: isn't there a requirement that any domain used in an App ID URI for SSO purposes be a valid, owned domain (like using azurewebsites.net for an Application Service)? Is localhost exempt from this somehow? Could this be related to this issue?

Similarly, debugging an SSO add-in seems to require providing pre-consent to the App Registration in advance. The side-loading steps seem to differ between Yeoman generated and Visual Studio projects. In this case (the latter), I was testing a no-consent scenario and cancelled the consent screen the first time I saw it and haven't been able to get it back. But I'm still not sure if this is related to the "401 Unauthorized" issue for the controller call...

Then there's the matter of using the forMSGraphAccess option for the getAccessToken() call, but that Office apparently can only prompt the user for consent for the AAD profile scope. I need additional Graph scopes. I'm also hoping to debug - and develop - an end-to-end multi-tenant solution that covers ALL scenarios: admin or user consent previously or not granted. Handling these variations in the flow is a bit of a nightmare! I'm still not certain if there are limitations for debugging this kind of an end-to-end solution using localhost vs. code and deploy and test to an Azure App Service tied to a valid domain for SSO usage in the related App Registration.

It gets confusing real fast, every single time I do an auth solution with M365, whether it's Outlook, PowerPoint or Teams. The samples are great, but the pitfalls are real and there are very many traps!

**Comment by elegault** [comment]
After thinking more about this issue over the weekend, and moreso in the context of the Outlook-Add-in-SSO project, the answer is clear as to why calls to SaveAttachmentsController with the Authorize attribute are failing: it is because there is no ASP.NET Identity integration in the project.  So, a previously authorized user is expected, but never actually signed in.  Until code for that is implemented, remove the Authorize attribute so this sample can be tested as is.

**Comment by elegault** [comment]
Ugh - correction: there IS Identity integration.  It's in the AzureADAuthController; it's Login method has to be called from the client script in MessageRead.js.  However, the conditions for calling Login() is entirely based on whether the dialogFallback() method is called in the script.  As the comments say: "For all other AAD errors, fallback to non-SSO sign-in".  I'm not certain that's true though: doesn't the Login() method always have to be called - even in SSO scenarios - so the user can be authorized and protected controller actions can be called?  So the problem seems to be that the user is never authorized if the sample is run in a first-run scenario where SSO is enabled?

**Comment by davidchesnut** [comment]
Hi Eric,

The Login method on AzureADAuthController is used when SSO has failed and you have to fallback to popping up a dialog to log in the user yourself. In the SSO success scenario it won't be called because the user is already signed in to Office and you get their user token from Office (thus no need to login again.) 

The [Authorize] attribute is configured in Startup.Auth.cs. You can see for example where it sets to check for ida:Audience. This is why you need to be sure the audience is set to your app registration GUID in the web.config. The token Office provides will contain this audience, and the [Authorize] attribute will enforce this check.

I'm not sure why this is failing for you so I'm still looking into this.

Cheers,
David

**Comment by kudecha** [comment]
Hi Everyone,

Thanks for your valuable inputs throughout this period.

I have finally figured out what's wrong and applied the change.
It's to do with the App Registration within Azure.

Here is the fix:
Update App Registration manifest file attribute 'accessTokenAcceptedVersion' with value '2' (it should be 'null' as default value).
Even though 'null' value is supposed to be used as v2 of SSO token (as per https://github.com/MicrosoftDocs/azure-docs/issues/19304), it does not.
I had to manually update manifest 'accessTokenAcceptedVersion' to '2' to receive correct token.

It would be great if documentation is updated with this information, to help other developers in future where they might be stuck forever like me.

Once again,
Thank you everyone.

Regards,
Jay

**Comment by davidchesnut** [comment]
Thanks @kudecha, this is super helpful!

I was able to reproduce this behavior by changing the registration type to "Accounts in any organizational directory (Any Azure AD directory - Multitenant)". The issuer and audience claims will change in the token causing the authorization failure in the sample. Then I edited the App Registration manifest to set 'accessTokenAcceptedVersion' to '2' as you said. Yep, now the token is correct.

I'll add a note to the docs and sample about this. Thanks!
