### ISSUE TITLE
Missing adal.js file in MessageRead.html

### ISSUE THREAD

**Issue by shahshyam** [OfficeDev/PnP-OfficeAddins#27]
I found Outlook.AddInSample project solution is missing some js file (adal.js) link in MessageReade.html under head section. Please check it

**Comment by ElizabethSamuel-MSFT** [comment]
@shahshyam Thanks for raising this issue.

@davidchesnut Can you take a look?

Thanks.

**Comment by davidchesnut** [comment]
I think this issue is referring to a really old sample that doesn't exist anymore. There are updated samples to take a look at here [https://github.com/OfficeDev/PnP-OfficeAddins/tree/master/Samples/auth](https://github.com/OfficeDev/PnP-OfficeAddins/tree/master/Samples/auth).

Please let us know if you encounter any issues in the newer samples. 
Thank you,
David
