### ISSUE TITLE
excel-shared-runtime-scenario not working

### ISSUE THREAD

**Issue by EthanVaz** [OfficeDev/PnP-OfficeAddins#87]
**URL of sample**

https://github.com/OfficeDev/PnP-OfficeAddins/tree/master/Samples/excel-shared-runtime-scenario

**Describe the bug**

On **npm run sideload**, Excel is started and there is an error saying **Error installing add-ins : One of more add-ins failed to download a required resource**

**To Reproduce**

1. Downloaded source code.
2. Follow steps mentioned in https://github.com/OfficeDev/PnP-OfficeAddins/tree/master/Samples/excel-shared-runtime-scenario
3. Excel starts but there is an error installing add-ins.

**Expected behavior**

Addin is installed and it works as mentioned in the sample documentation.

**Screenshots**

![image](https://user-images.githubusercontent.com/69612514/90236954-1a144d00-de41-11ea-9432-a9e4aa32e1ed.png)

![image](https://user-images.githubusercontent.com/69612514/90236985-2bf5f000-de41-11ea-9cdf-098c535fc514.png)

**If it helps, this is content of OfficeAddins.log.txt**

![image](https://user-images.githubusercontent.com/69612514/90237003-34e6c180-de41-11ea-8dc3-54a18fc4ee0e.png)

![image](https://user-images.githubusercontent.com/69612514/90237009-37e1b200-de41-11ea-91f7-8b8a009ec368.png)

**Environment**
- Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
- Host [Excel, Word, PowerPoint, etc.]: Excel
- Office version number: Microsoft 365 Apps for Enterprise, Version 2009 (Build 13205.20000), Beta Channel
- Operating System: Windows 10 Pro
- Browser (if using Office Online): NA

**Additional context**

Clicking on any of the buttons in ribbon does nothing.

**Comment by AlexJerabek** [comment]
Hi @EthanVaz, 

I believe your issue was related to expired certificates being used. PR #89 should have addressed this. Could you please retry the sample installation instructions with the new certificate step? I'll relist them below.

0. Clone the repo and navigate to the "Samples\excel-shared-runtime-scenario" folder.
1. `npx office-addin-dev-certs install --days 365`
2. `npm install`
3. `npm run build`
4. `start npm start`
5. `npm run sideload`


Please let me know if that helps. Thanks!
