### ISSUE TITLE
Office.ASP.NETCoreReactAddins can not be loaded the add-in module by Excel in debugging.

### ISSUE THREAD

**Issue by yhayak872** [OfficeDev/PnP-OfficeAddins#88]
**URL of sample**
https://github.com/OfficeDev/PnP-OfficeAddins/tree/master/Samples/Office.ASP.NETCoreReactAddins

_URL linking to the sample that has the bug._
https://github.com/OfficeDev/PnP-OfficeAddins/blob/master/Samples/Office.ASP.NETCoreReactAddins/excel-js/manifest.xml

**Describe the bug**
In debugging, Excel invoked by Visual studio could not load Add-in module from local web site.

_A clear and concise description of what the bug is._
The manifest.xml file specified the Add-in page url. But it's wrong.
Line 72 of manifest.xml specified below.
     Url id="Taskpane.Url" DefaultValue="~remoteAppUrl/taskpane.html"
But there is not taskpane.html in the sample project.
It must be index.html I think.

**To Reproduce**
After change it, It's working fine.

1. Clone sample folder on Visual studio 2019
2. Follow step to build Add-in project and solution
3. Debug start
4. Local web server started on Visual studio and Excel started
5. Excel can not load add-in module. ( waiting to load forever )

**Expected behavior**
Add-in module is loaded and Task pane can be used.

_A clear and concise description of what you expected to happen._
I only want to execute sample in original.

**Screenshots**

_If applicable, add screenshots to help explain your problem._

**Environment**
- Platform [PC desktop, Mac, iOS, Office Online]: PC Desktop
- Host [Excel, Word, PowerPoint, etc.]: Excel
- Office version number: Office 365 16.0.12527.20880 64Bits
- Operating System: Windows 10 Home
- Browser (if using Office Online): ______

**Additional context**
none

_Add any other context about the problem here._
none
--
Thank you to provide this sample.
Regards.

**Comment by aafvstam** [comment]
It is not what I see (it loads on my machine and able to stop on a breakpoint), technically I think @yhayak872 is right and the URL in the manifest should be index.html

The unmodified project works however on my machine (I live streamed it on YouTube so if you have a couple of hours you can look back what I did 😉).

Out of the box it did work for me:

![image](https://user-images.githubusercontent.com/5305682/93535686-c4532900-f947-11ea-8dd1-3e7a68c4d001.png)

The URL in the manifest.xml will reflect on runtime though like this:

![image](https://user-images.githubusercontent.com/5305682/93535736-e77dd880-f947-11ea-9c75-7731d742d341.png)

After changing the manifest to index.html you will get this:

![image](https://user-images.githubusercontent.com/5305682/93535787-054b3d80-f948-11ea-8612-c86451253d5f.png)

Either way in both scenarios I see the page to be resolved to https:.//localhost:44340 (as defined in the VS settings) 

![image](https://user-images.githubusercontent.com/5305682/93536073-8e627480-f948-11ea-9857-d727bf61bd99.png)

My guess is that .NET Core is resolving the URL to index.html, not sure why this is not happening with @yhayak872 
(maybe the issue is related to the fact that the URL sometimes is given ending on $$$$3 ?)

The livestream where I debugged this can be found here:
[Live stream here](https://youtu.be/cZKIT_K75MM)

**Comment by yhayak872** [comment]
Thank you to report many information and suggestions. Your live stream was very helpful for me.
After your report, I checked again my project and executed.
Curiously, My Project worked fine too with original URL path ( it is "~remoteAppUrl/taskpane.html" ).
But I can not understand why it did not work before because I have not modified anything but above URL.
After my report, my machine had two updates for .NET- flamework ( KB4576484, KB45707323 ) and these may be related this.
.NET core resolves the requested URL to index.html as you say, therefor any URL was working as long as the file name doesn't match. ( ex: "~remoteAppUrl/anything.html" or "~remoteAppUrl/")
Thanks a lot.

-PS-
This is not related to above but I can not set breakpoint well on Apps.js as you did.
VS said "the breakpoint will not currently be hit. ... " like this.
![VS-Breakepoint](https://user-images.githubusercontent.com/68672288/94233367-bc484a00-ff42-11ea-9f6d-80b6361b1690.png)

I'm checking continuously to resolve this. (I'll ask again this to other proper forum.)
Best regard.

**Comment by yhayak872** [comment]
This is a post-report of this issue.
Repairing my Visual Studio resolved the breakpoint issue.
Perhaps the first problem of not loading the add-in module is for the same reason too.
My Visual Studio was updated several times while debugging this add-in project, so it's possible that Visual Studio wasn't working properly.

Best regard.
